services:
  app:
    platform: linux/amd64
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && node main.js"
    ports:
      - "3000-3003:3000-3003"
      - "8080:8080"

  viaproxy: #use this service to connect to an unsupported minecraft server versions. more info: ./services/viaproxy/README.md
    image: ghcr.io/viaversion/viaproxy:latest
    volumes:
      - ./services/viaproxy:/app/run
    ports:
      - "25568:25568"
    profiles:
      - viaproxy
